### PR TITLE
added quiet flag

### LINKED ISSUE #48: Add a `-q`/`--quiet` config option
# 🚀 Feature Request

## Is your feature request related to a problem? Please describe.
Right now you basically always get full info-level output to the command line unless you know how to disable it with the `LOG_LEVEL` environment variable. This isn't a great user experience, especially as we're adding the console reporter.

## Describe the solution you'd like
The `-q`/`--quiet` option should basically turn off all the console logger. No log messages of any level should appear.

### PR DESCRIPTION
**Pull request by krishnaduttPanchagnula**
Closes #48

### CODE REVIEW

**Review by tarkatronic — COMMENTED** [review]
Hi @krishnaduttPanchagnula thank you for continuing to contribute to this project, and apologies for the delay here!

I suspect this is not the right approach to this fix; in fact, I think this has inadvertently stopped the command from working at all... I checked out your branch and when I try running the command, nothing seems to be working now:
```sh
❯ go build .
❯ ./vulnbot
❯ ./vulnbot --help
❯ echo $?
0
❯ ./vulnbot -q
❯ ./vulnbot quiet
❯ ./vulnbot asdf
```
Instead of adding a new command for this, you will probably want to add a new persistent flag to the root command, like the ones seen currently at the bottom of `cmd/root.go`. You will then want to use the value of that flag to decide what log level to set in the logger, as seen in `logger/logger.go` line 38. What I am not certain of right now is, what is the best way to pass that log level? And, how can we ensure that the log level is set appropriately for all instantiations of the logger, since it is using `sync.Once`

**Comment by krishnaduttPanchagnula** [comment]
@tarkatronic This latest code should solve your issues

**Comment by tarkatronic** [comment]
> > You will then want to use the value of that flag to decide what log level to set in the logger, as seen in `logger/logger.go` line 38
> 
> If i understand it rightly @tarkatronic , the solution is set a flag --quiet which will stop the logger from enabling rather than setting the log_level right?

Hi @krishnaduttPanchagnula. Sorry no, not exactly. We do want to set the log level, because there will be other ways to modify this in the future as well (such as with a `--verbose` flag).

What we need is a single place (probably in `cmd/root.go`) that will take all command lines flags into consideration, and then make sure the log level is set appropriately.

I did find in [this example](https://github.com/rs/zerolog#leveled-logging) that there is a `zerolog.SetGlobalLevel` that we can call, which should handle setting the appropriate level. Additionally there is a `zerolog.Disabled`, which should do what we want.

So putting that together, we need a piece of code that sets the log level, and when `--quiet` is passed in, that log level is `zerolog.Disabled`.

Does that make sense?

**Comment by tarkatronic** [comment]
Closing in favor of #69

**Pull request closed without merging**
