### PR TITLE
Normalized local timestamps to Raw UTC 

### LINKED ISSUE #60: Timestamps should be normalized to UTC and formatted by reporters
# 🚀 Feature Request

## Is your feature request related to a problem? Please describe.
Right now, timestamps are generated using the time zone of the computer that's running it. This makes it somewhat variable and, especially when we create a Datadog reporter as discussed in #45, we will want it to be normalized and consistent.

## Describe the solution you'd like
When we generate the `reportTime` in `internal/scan.go`, we should make sure that it is in UTC. Additionally, we should send just the raw timestamp to the reporters and let them handle formatting. This allows each reporter to format it in a way that is appropriate to that individual reporter.

## Additional context
This is a follow-up to https://github.com/underdog-tech/vulnbot/pull/56#discussion_r1206055742

### PR DESCRIPTION
**Pull request by krishnaduttPanchagnula**
Closes #60

### CODE REVIEW

**Comment by tarkatronic** [comment]
Hi @krishnaduttPanchagnula, welcome and thank you so much for contributing!

I believe this will cause one issue however, which the tests should confirm. The second part of this fix is that the reporters are currently expecting the RFC1123 formatted string. So the reporters will need to be updated to expect this Unix timestamp instead, and convert that to a formatted string. If you could get that added, I would be very happy to merge this for you!

**Comment by krishnaduttPanchagnula** [comment]
> need to be updated to expect this Unix timestamp

@tarkatronic do you want me to pass the unix as string in those reporters?

**Comment by krishnaduttPanchagnula** [comment]
@tarkatronic i changed the reporters methods, interfaces and tests to reflect the change in the timestamp.

**Comment by tarkatronic** [comment]
@krishnaduttPanchagnula Great, thank you! Looking at the results of the tests here, it looks like some of the references to the string "now" in the tests may not have been updated yet. That was a hard-coded test string that I was passing in as `reportTime`, and checking for in my expected output. If you haven't been already, I would recommend running `go test -v ./...` after you make your changes, to ensure the tests are still passing.

I've looked at this a bit more deeply and realized another thing. With this change, when the message goes to Slack, the time is reported as the Unix timestamp (for example, `1685196631`). What I didn't think of before is that calling `.Unix()` converts to a 64-bit timestamp, but what would be ideal to give to the reporters is a `time.Time` struct. That would mean that we don't actually need to call `.Unix()`. That way the reporters can then call `.Format()` on the time to get a nicely formatted string like they have now.

If you like, I can get this merged in and make those small fixes myself, or I am happy to let you finish that piece up as well!

**Comment by krishnaduttPanchagnula** [comment]
> If you like, I can get this merged in and make those small fixes myself, or I am happy to let you finish that piece up as well!

Hi @tarkatronic I have fixed the test which was causing the error. I can take up other issues, if you can take up time.Time change.
image

**Comment by tarkatronic** [comment]
@krishnaduttPanchagnula That sounds great! As long as the tests pass, I can get this merged in for you and then I can take over. I'm going out of town with family for a couple of days with family though so I might be a little slow in that part.

**Review by tarkatronic — APPROVED** [review]
Looks great; thank you for taking this on and working through it with me @krishnaduttPanchagnula!

**Comment by krishnaduttPanchagnula** [comment]
> I'm going out of town with family for a couple of days with family

Hope you have spend quality time with your family...!

**Pull request merged**
