### PR TITLE
feat: Switch to viper for configuration

### PR DESCRIPTION
**Pull request by JoseAngel1196**
## Task

Fixes https://github.com/underdog-tech/vulnbot/issues/32

## Description

* I’m representing the Viper library with a struct and creating the client using a public function called NewViper. To use it, I have implemented struct functions, similar to how we do it in the Slack package. We now have LoadConfig and LoadEnv.
* When we run the project (e.g., go run scan...), we default the --config flag to the name of the config.toml. I have updated the flag value to include the current working directory (cwd) and the name of the config file. This change shouldn’t break anything, but I had to do it to make the LoadConfig dynamic and easy to test. We can now specify the configPath in the test file.
* Additionally, I have renamed the TomlConfig to just Config, as this change is applicable to any type of config file.
* I’m open to suggestions here, but I have created a /testdata folder to include two config files that I can use to test the LoadConfig and LoadEnv methods.

### CODE REVIEW

**Comment by JoseAngel1196** [comment]
@tarkatronic packages excluded 😊

**Comment by tarkatronic** [comment]
> @tarkatronic packages excluded 😊

Beautiful, thank you! Hmmm looks like now `gosec` is unhappy.

```
[/github/workspace/config/config.go:88] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    87: 	v.AutomaticEnv()
  > 88: 	v.ReadInConfig()
    89: 



[/github/workspace/config/config.go:71] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    70: 
  > 71: 	if v.Unmarshal(&config); err != nil {
    72: 		log.Fatal().Err(err).Msg("Unable to unmarshal config.")



[/github/workspace/config/config.go:69] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    68: 	v.SetConfigType(strings.TrimLeft(extension, "."))
  > 69: 	v.ReadInConfig()
    70: 
```

It looks like in both of those cases you are not capturing the return value of the function. That's especially problematic in the first instance, as your are attempting an error check, from a previous error value!

**Comment by tarkatronic** [comment]
Strange, I definitely hit "Cancel" on that review just now. Ignore all that...

**Review by tarkatronic — APPROVED** [review]
This looks like a great starting point for this switch -- this unlocks so many more possibilities for configuration! Thanks for tackling this @JoseAngel1196!

**Pull request merged**
